### ISSUE TITLE
Slow initial load / rendering

### ISSUE THREAD

**Issue by MikeBild** [astoilkov/jsblocks#12]
My first my example app

https://github.com/SubKit/sk-todo-app/tree/master/src/jsblocks

the initial load and rendering time is slow. It flickers when starting. Any ideas?

**Comment by astoilkov** [comment]
Hi,

I have run the application but I don't observe any problems with the performance. Could you be a little more specific? The slow part is the time to load all resources (javascript and JSON data). The example is currently loading two items...maybe you have tried with more and the performance problem was with it?

Thanks for any additional info in advance.

**Comment by MikeBild** [comment]
Ohh, yes. The empty <li> template is visible, within a (re)load with disabled resource caching. It's okay. Any suggestions for enable / visible the view only if data (from remote/promise resolved) is available? I'm looking for functionality similar to Angulars Router resolve. (https://docs.angularjs.org/api/ngRoute/provider/$routeProvider)

**Comment by astoilkov** [comment]
From what I understand you want to make the Todos view only visible when the data is retrieved from the server, right? If this is the case you could do something like the code below which could be positioned in the Todos View `init()` method:

> The `isActive()` property of the View determines if it is visible or not

```javascript
this.isActive(false);
this.todos.updating.on('change', blocks.partial(this.isActive, true));
```

The entire code based on your example should be something like this:

```javascript
App.View('Todos', {
  todos: Todos(),
  newTodo: Todo(),
  init: function () {
    this.todos.get();
    this.isActive(false);
    this.todos.updating.on('change', blocks.partial(this.isActive, true));
  },
  refresh: function () {
    this.todos.get();
  }
});
```

Please do not hesitate to shoot more questions if I didn't understand you correctly.

> Side note: AngularJS Router provides a lot of complexity in my opinion. Most of the things that could be done using the Router could be replaced with simpler approaches. If you are interested in jsblocks routing mechanisms you could take a look [here](http://jsblocks.com/learn/view-routing-and-history)

**Comment by MikeBild** [comment]
That's looks good. I'll try this. Thx

@Angular: Yes I share your opinion.

**Comment by MikeBild** [comment]
blocks.partial is not in API docs. What is the functionality?

**Comment by astoilkov** [comment]
Yes. I am working on that part. It is not part of the API docs because it is separate module that actually I will represent as a separate library. It is like Underscore and Lodash but have a lot of performance benefits over them.

In this case blocks.partial passes any number of arguments to the function specified. In this case the this.isActive observable(and any observable is a function) is passed true. So it is the same as doing:
```javascript
blocks.isActive(true);

// i used blocks.partial because otherwise the code would look like this
var _this = this;
this.isActive(false);
this.todos.updating.on('change', function () {
  _this.isActive(true);
});
```

In the general case you could expect that blocks have the same methods like [Underscore](http://underscorejs.org/#partial) or Lodash[https://lodash.com/docs]. For now you could look there for methods or just remove that module if you want to use other library. You could remove it from the [Custom Build](http://jsblocks.com/download#custom-build) section in the download page.

**Comment by MikeBild** [comment]
Ok. Sounds interesting. You want to separate a library for observable / stream operations like RxJS, highlandjs?

**Comment by astoilkov** [comment]
Actually its a separate library for working with data. blocks.observable is using the library / module to provide seamless way for working with the data that inside the observable. Stream operations will not be available at first but I am definitely thinking of including them. I hope I will have enough time soon to release it.

**Comment by MikeBild** [comment]
isActive doesn't help - it flickers on page reload (cache disabled)

**Comment by astoilkov** [comment]
Yes. This is expected. This is the problem with client-side frameworks. The result is not valid until the JavaScript kicks in which always at least of couple of milliseconds. That's why I created [server-side rendering](http://jsblocks.com/learn/introduction-why-jsblocks#server-side-rendering).

However, if you don't want to go too advanced with server-side rendering you could fix your problem by hiding the view using inline CSS as shown below:
```html
<!-- this will make the view not visible from the start and when the framework kicks in will make it visible-->
<main data-query="view(Todos)" style="display:none">
...
```

Let me know if this works for you. :)

**Comment by MikeBild** [comment]
style="display: none;" helps ...
