### ISSUE TITLE
requirejs: additionals functions/blocks in view when has created

### ISSUE THREAD

**Issue by adrianrey05** [astoilkov/jsblocks#125]
Hello @astoilkov ,
I use requirejs for the controllers, models and collections load on demand.
I can add functions as when the view is already created?
i try in the init func, but in the doc says you can not do.
can you help me?

```javascript

var app = blocks.Application({
  history: 'pushState'
});

function addView(name, route, template, controller){
 var config = {
	options: {
	   route: route,
	   url: template
	}
 }
 
 if(controller){
	config['init'] = function(){
	   var self = this;
	   require([controller], function(ctrl){
		  for(var item in ctrl){
			 if(!self[item]){
				self[item] = ctrl[item];   
			 }
		  }
		  if(self['load']){
			 self.load();//init func
		  }
	   });
	};
	app.View(name, config);
 }else {
	app.View(name, config);
 }
};

addView('Home', '/', '/views/index.html');
addView('Tags', '/tags', '/views/tags.html', './controllers/tag');
addView('Proyectos', '/proyectos', '/views/proyectos.html', './controllers/proyecto');
addView('Login', '/login', '/views/auth/login.html', './controllers/login');
```
controller tag
```javascript
define(["models/tag"],
function(tag){

   return {
      list: tag.collection(),
      load: function(){
         var self = this;
         self.list.read();
      }
  }
});
```
model tag
```javascript
define(["app"], function(app){
   
   var tagModel = app.Model({
      id: app.Property(),
      tag: app.Property(),
      color: app.Property()
   });

   var tagCollection = app.Collection(tagModel, {
      options: {
         read: {
            url: '/api/tags'
         }
      }
   });
   
   return {
      model: tagModel, 
      collection: tagCollection
   };
});
```

this is the error

![image](https://cloud.githubusercontent.com/assets/5314570/11996019/a11c6422-aa39-11e5-9cac-a55dcd5bac23.png)

PS: forgiveness for opening and closing the same issue

Thanks for you help.
Bye!

**Comment by Kanaye** [comment]
Hey @adrianrey05!

Adding functions/properties to a ``View`` in the ``init``-function works but has some disadvantages compared against using the constructor ``App.View``.

For Example:
A function added in the ``init``-function will not be bound to the ``View``'s context and will therefore get executed in the wrong context in some cases.

The definition is failing in your case because requirejs is asynchronous.
The following will happen in your example:
1. jsblocks will figureout that it has to render  the view ``Tags`` and call the ``init``-function.
2. In the init funciton requirejs will *start* doing it's job and requesting the files.
3. jsblocks will continue to render the view as the ``init``-function is done.
4. jsblocks will fail as ``list`` is not defined (yet).
5. rendering ended
... some time later ....
6. requirejs will call the function that declares the ``list`` property of your view and other properties.
7. nothing: As jsblocks can't even know about the new properties it will not try to rerender the view.

As far as I know jsblocks does not provide a way to initialize Views async and I'm not sure that it is worth adding such a feature. 

What do you think @astoilkov ?

**Comment by adrianrey05** [comment]
Hi @Kanaye,
Thanks for answering.

Is there a way to render the view when require.js finished?

**Comment by astoilkov** [comment]
I agree with @Kanaye. In my opinion there is no need for async initialization of views. @adrianrey05 you could just put the properties you will be creating in the constructor and then in the requirejs function fill the values for them. The View will be rendered initially and then you will just fill the values to the View properties and the View will update itself to correspond to the data. Does this work for you @adrianrey05?

**Comment by adrianrey05** [comment]
Hi @Kanaye, @astoilkov 

Okay, I will follow the rules.
Thank you for your help.
