### ISSUE TITLE
observable event handle not binding correctly to DOM

### ISSUE THREAD

**Issue by thaapaniemi** [astoilkov/jsblocks#129]
At least click events don't bind after changing view if observable is changed in code with `App.View('ViewX').value(newVal);` (`this.value(newValue)` works).

Example: https://github.com/thaapaniemi/jsblocks_i1

What is the "right" way to update the observable from locations where `this` doesn't point to the current View object?

**Comment by Kanaye** [comment]
Hey @thaapaniemi,

You can access properties of a view like so: ``App. ViewX.myObservable()``.

But keep in mind that this will only work after the application finished initializing. 

Have a nice day!

**Comment by Kanaye** [comment]
Whoops sorry, 
I was on my mobile while answering this and didn't read your example, so just ignore my previews comment as it's not the solution.

It seems that this is a bug because your way is a "right" way.

After taking a first look at your example I think this *could* be an issue with the views context.
But that is just a first guess. 
I will dive into that deeper tomorrow as I have unfortunally no time to spent yet.

I will post here when I'm making progress.

**Comment by Kanaye** [comment]
Hey @thaapaniemi,
thank you for reporting this issue.
We had a serious problem with the views context getting overwritten in some cases.
I fixed it in #130 so your code will work in the next release.

For now you can modify [this line](https://github.com/thaapaniemi/jsblocks_i1/blob/98792fa1012ffdd63e00b8ab903625c5f8d6589a/a.html#L6) to use ``$root.FirstView.click`` instead of ``$view.click``.

**Comment by thaapaniemi** [comment]
Thank you for fast response. The quick fix works great with current code for now.
