### ISSUE TITLE
How can I use route GET?Thank you!

### ISSUE THREAD

**Issue by wy373226722** [astoilkov/jsblocks#136]
![qq20160309-1 2x](https://cloud.githubusercontent.com/assets/6657330/13641619/189d6220-e654-11e5-9a73-9f4e67c60c64.png)
![qq20160309-2 2x](https://cloud.githubusercontent.com/assets/6657330/13641624/1a56d2b8-e654-11e5-8e83-600f3f21b1a6.png)
I

**Comment by Kanaye** [comment]
Hey @wy373226722! 
It's not possible to register routes to express-apps from ``server.express()`` because jsblocks registers a habdler for all routes serving the default view (with the route '/'). The next release will contain a function ``blocks.midddleware()`` that can be registered in an express app.  You could build jsblocks yourself for now. 

Greetings from Germany

**Comment by wy373226722** [comment]
Thank you very much! @Kanaye
