### ISSUE TITLE
Evaluation of index in 'for' loop for modified collection is sometimes incorrect

### ISSUE THREAD

**Issue by rfreedman** [astoilkov/jsblocks#138]
Steps to reproduce:
- create model containing an observable array
- create a template that renders the items in the array, along with the loop index
- add two items to the array
- delete the first item from the array
- result: the rendering of the single remaining row contains evaluations of the index as both 0 and 1, in the same iteration

See the jsfiddle at https://jsfiddle.net/rfreedman_chariot/b1qmmf9b/6/
Perform the above steps, and notice that, for example, the first cell of the first row of the table
looks like:
```
<td data-id="23" class="row_1_col_1">
      <input type="text" data-query="val(name)" placeholder="Name" data-id="24" name="typeDefinition.fields[0].name" class="x-text-field row_2_name" value="">
</td>
```

when it is expected to be 

```
<td data-id="23" class="row_1_col_1">
      <input type="text" data-query="val(name)" placeholder="Name" data-id="24" name="typeDefinition.fields[0].name" class="x-text-field row_1_name" value="">
</td>
```

**Comment by Kanaye** [comment]
Hey @rfreedman.
That's strange as it doesn't occur in firefox but in chromium. I'll look into this.

I also have some optimisations for you:
You are using ``{{parseInt($index) + 1}}`` to increment the rendered result. 
You use ``parseInt()`` because ``toString()`` is called on the observable. 
You can call the observable to get the expected number. 
That's a liitle bit faster then converting it to a string and then parsing it to a number. 
The expression would look like: ``{{$index() + 1}}`` what's also easier to read :smile: .
You can simplify your delete button from 
 ```html 
 <button data-query="click($root.deleteRow)" data-idx="{{$index}}" class="x-icon x-icon-trash">Delete</button>
 ``` 
 to 
 ```html
  <button data-query="click($root.deleteRow, $this)" class="x-icon x-icon-trash">Delete</button>
 ```
 your delete function would look like that: 
```javascript
 /* ... */
  self.deleteRow = function(e, row) {
     self.fields.remove(row);
  };
 /* ... */
```
That's a little bit easier to read and a little bit faster because blocks does not need to update the dom for the ``data-idx`` property.

**Comment by rfreedman** [comment]
Thanks for looking into this. I'm seeing odd behavior in this code in Firefox too, just not the same behavior.
Actually, I noticed the problem in Firefox first. I'll try to come up with simple example that demonstrates the problem in Firefox.

**Comment by Kanaye** [comment]
Okay it was the same bug in Firefox. 
Im not sure why I missed i t the first time. 
Maybe I'm just going crazy...

I created PR #139 with a fix for it, so it will be fixed in the next release.

**Comment by rfreedman** [comment]
On Sun, Mar 13, 2016 at 4:55 PM, Joscha Rohmann <notifications@github.com>
wrote:

> #139


Thanks! We'll check it out.


------------------------------
Rich Freedman
  <http://greybeardedgeek.net>  <http://twitter.com/#!/greybeardedgeek>
<http://www.linkedin.com/profile?viewProfile=&key=13484238&trk=tab_pro>
