### ISSUE TITLE
Anyway to avoid #hash scrolling to top?

### ISSUE THREAD

**Issue by abacaj** [astoilkov/jsblocks#15]
Running the sample shopping application and navigating between `boys, girls, babies etc` while being lower on the page causes the page to scroll to top.

Is there anyway to prevent this?

**Comment by astoilkov** [comment]
It seems that the problem have two sides. The #hash and the scrolling. You could fix the #hash using on of the two approaches:
1. Replace the `<a>` tag with other tag and swap the corresponding styles
2. In the `Sidebar.selectedCategory()` method call `preventDefault()` on the event
```javascript
selectCategory: function (e, category) {
	Sidebar.category(category);
	e.preventDefault();
}
```

However, after doing this the first time you click on a sidebar item it still goes to the top of the page. This is caused from the fact that the images are not loaded. After you select the same item for the second time it stops going to the top. What I can think of for solving this problem is iterating over all items and rendering the images in a hidden element. Another approach would be hardcoding the `<img>` height in CSS but this will cause losing the responsive design in the example.

**Comment by astoilkov** [comment]
I am closing this one. If you need additional information reopen the issue or open a new one.
