### ISSUE TITLE
Prevent the {{expressions}} from showing up in the client at loading time

### ISSUE THREAD

**Issue by antoninadert** [astoilkov/jsblocks#156]
When I access an application with jsblocks, I can see the {{expressions}} not evaluated yet in the app when I start or press F5 repeatedly.

Can this be fixed ? (as it is SSR I supposed there was a way not to show them on client start)

**Comment by Kanaye** [comment]
When using server side rendering jsblocks doesn't show the ``{{expessions}}``. 
In client side only rendering there is no way for us to hide them, because they are shown before js is evaluated / the dom is ready and when the dom is ready we are rendering the content so there is no reason to hide them there.

You can see that there are no expressions show on load in the [shopping example](https://github.com/astoilkov/jsblocks-shopping-example).
Just download/clone it and run ``npm install`` and ``npm run node``.

**Comment by antoninadert** [comment]
Actually I just did that but it still displays the non-evaluated {{expression}}.
Is it because of local host? Sadly I cannot try on a production server yet
![untitled](https://cloud.githubusercontent.com/assets/8929314/20886692/8ff59360-baf7-11e6-8251-19e9ea0d8499.png)

**Comment by Kanaye** [comment]
Hi!
Sorry I still can't reproduce your issue.
Here is an screenshot of the shopping-example with server side rendering enabled with (in browser) disabled javascript.
Okay most of the page won't work without javascript but it still loads without the expressions:
![shopping-example-no-js](https://cloud.githubusercontent.com/assets/5108989/20887517/3896ee6c-bafb-11e6-9c94-df4dc68a792d.PNG)

**Comment by antoninadert** [comment]
For your information to take the screen shot I just hold f5 so it reloaded repeatedly. (as the expression is quickly evaluated after)
Do I need to do something special to  benefit from SSR apart from npm install / start?

**Comment by antoninadert** [comment]
Well I just 'npm run node' again without changing a thing and... this now works. 
I don't understand what caused the first issue ! thanks for your help anyway
