### ISSUE TITLE
Dynamic View Containers

### ISSUE THREAD

**Issue by derkan** [astoilkov/jsblocks#20]
Hi,
I have a index.html structure like:
```html
<header id="header" data-query="view(HeaderView)"></header>
<section id="main">
    <aside id="sidebar" data-query="view(SideBarView)"></aside>
    <section id="content"></section>
</section>
```
In SideBar view, there are links for content like `navigateTo(DasboardView)` or `navigateTo(UserProfileView)`. 

I am loading views with requirejs like this:
```js
define(function (require) {
   var App = blocks.Application();
   var HeaderView = require('./views/HeaderView');        
   var UserProfileView = require('./views/UserProfileView');        
   App.start();
});
```

### What I want is: 
Load that clicked link target view in `content` section dynamically. With 'dynamically', I mean loading of View without defining it in html, for example without defining these in content section:
```html
<div class="container" data-query="view(DasboardView)"></div>
<div class="container" data-query="view(UserProfileView)"></div>
```
Is it possible with jsblocks framework without breaking route history support?

**Comment by astoilkov** [comment]
Hi,

* If you mean not defining them directly in html you could use the [View Lazy Loading] (http://jsblocks.com/learn/view-view-lazy-loading) and define them in an external html file

* If you mean you don't want to repeat the same code again. I have a suggestion that if you agree I can implement. Instead of defining all the views individually when you want to share the div for more that one view you could do like this:
```html
<div class="container" data-query="view(DasboardView, UserProfileView)"></div>
```

or

```html
<div data-query="each(views)">
  <div class="container" data-query="view($this)"></div>
</div>
```

Please provide more information if I have not understood you correctly.

**Comment by derkan** [comment]
I liked both options. But, what I mean is a bit different. Lazy loading is only fetching template for the view. 
But for my case both rendering and initializing of View will be done dynamically. So, there is a need for a common container view. Maybe a new navigation function can be developed to render any View in a specific HTML container element like:
```js
navigateInto(ContainerElementSelector, View, args_for_navigation)
```
Where ContainerElementSelector is a selector for HTML element(style class or id), View is any View defined, and latter parameters which are same as current `navigateTo`. For my HTML example:

```html
<section id="content"></section>

<div id="menu">
   <a href="#" data-query="navigateInto('#content', UserProfileView);">Users</a>
</div>
```
This will give easy implementation for web Admin style SPA's. There are too many links and corresponding views for this type of applications.

### Furher improvement proposal for `navigateInto`:
For further improvement, View parameter maybe a string value holding any view uri like 'app/views/UserView'. That navigate function will fetch and initialize View object it into given container like:
```html
<section id="content"></section>

<div id="menu">
   <a href="#" data-query="navigateInto('#content', 'app/views/UserProfileView');">Users</a>
</div>
```

**Comment by astoilkov** [comment]
Just one question. What will be the difference between this:

```html
<section id="content"></section>

<div id="menu">
   <a href="#" data-query="navigateInto('#content', UserProfileView);">Users</a>
   <a href="#" data-query="navigateInto('#content', DashboardView);">Users</a>
</div>
```

and this:

```html
<section id="content" data-query="view([UserProfileView, DashboardView])"></section>

<div id="menu">
   <a href="#" data-query="navigateTo(UserProfileView);">Users</a>
   <a href="#" data-query="navigateTo(DashboardView);">Users</a>
</div>
```

The two thigs will do the same thing. Howerver, I believe the `view()` is more elegant solution because you are placing the `view()` query directly onto the element instead of point to it using a selector. Also this way we could avoid one additional query that needs to be learned.

**Comment by derkan** [comment]
Hi Antonio, 
Solution you showed is really a neat, I appreciate that. Thanks for answering my questions (even at weekend).

I am planning to convert a JQuery based web site to SPA with new features. There will be minimum 40 `Views`. To be able to use this logic, every view should be initialized and must be defined in `content section`  within `data-query` tag; even if user may not use most of the views for that session. Also I will have to define views which are not be allowed to access for some loginned users(not authorized for a set of views maybe). 
 
- Will initializing too many views, will slow down app initializing(especially on mobil devices)?
- Will use too much memory?
- JS loading from network will take more time?
- Will slow down app?

Currently I have only a few views and they are light. Have you implemented big SPA's and had these problems that worries me with `jsblocks framework`?

**Comment by astoilkov** [comment]
40 views are no problem for the performance or memory consumption of your app. In general jsblocks should be more effective than jQuery in large applications because it brings complexity down and optimizes for particular cases. However, here are some things you should be careful about:
 * A lot of data in your 40 views. That means `blocks.observable()` variables, `App.Collection()` and `App.Model()`. By a lot I mean more than 500 `blocks.observable()` for example.
 * A lot of dependent variables. By that I mean if you have one `View` that have a variable that when changed updates another 100 variables in the same or other views
 * You are filtering huge amounts of data. Around 300k

The network traffic will be dependent on the file size of your JavaScript files. However, jsblocks should significantly minimize the code of your application comparing to a jQuery implementation. You could observe the difference between TodoMVC Application implementation for [jsblocks](https://github.com/astoilkov/jsblocks-todomvc) and [jQuery](https://github.com/tastejs/todomvc/tree/gh-pages/examples/jquery).

> Note that these are general suggestions and the numbers could vary based on your implementation complexity

**Comment by derkan** [comment]
Thanks Antonio, Happy to learn those. I'll try it.
