### ISSUE TITLE
Is there a way to have 2 instances of a view with different options on a page?

### ISSUE THREAD

**Issue by clarkeadg** [astoilkov/jsblocks#57]
Hi astoilkov,

I am having difficulty trying to make a view re-usable so that 2 copies can coexist on a page at the same time with different options.

Is there any way to pass options to a view with a data-query?

I would like to do something like this:

```html
data-query(view(MyView, { id: 1}))

data-query(view(MyView, { id: 2}))
```

However, the view method does not accept options as a parameter.

I tried making a custom data-query like this but am struggling to get it to work.

```html
data-query(portlet(MyView, { id: 1}))

blocks.queries.portlet = {
    preprocess: function (param1, param2) {
        this.html('<div id="'+param1+'" data-query="view('+param1+')"></div>');
        blocks.query(param2);
    }  
};
```

**Comment by astoilkov** [comment]
Hi Brian,

The straight answer is no. 

The longer answer is that once there was exactly the same API. You would pass arguments to the `data-query` `view` method and it would have been passed to the View constructor. However, I decided that a View will always be one. This was because such a scenario should be achieved using a component of some kind. Before custom elements are implemented in jsblocks achieving this could be done using the `template data-query`:

```html
<script id="Profile" type="blocks-template">
  <h1>Profile</h1>
</script>

<div data-query="template(Profile, currentProfile)">
</div>
```

**Comment by clarkeadg** [comment]
Ok, thank you.  I will use templates.
