### ISSUE TITLE
Render query isn't working

### ISSUE THREAD

**Issue by zombiQWERTY** [astoilkov/jsblocks#58]

**Comment by zombiQWERTY** [comment]
And ifnot query not correctly working

**Comment by astoilkov** [comment]
Could you provide more information on your scenario. There are tests about [render](https://github.com/astoilkov/jsblocks/blob/master/test/spec/query/queries.js#L328-458) and [ifnot](https://github.com/astoilkov/jsblocks/blob/master/test/spec/query/queries.js#L127-200) which are passing for every built and I guess that it some custom scenario that's failing.

**Comment by zombiQWERTY** [comment]
Here is my console with errors_______________________________С уважением, zombiQWERTY

**Comment by zombiQWERTY** [comment]
Here is my console with errors
![Uploading Снимок экрана 2015-06-21 в 13.47.18.png…]()

**Comment by zombiQWERTY** [comment]
Here is my console with errors
http://oi59.tinypic.com/dh5y6r.jpg

**Comment by astoilkov** [comment]
Yeah. I understand now. The console messages are not correct but I have already fixed them couple of weeks ago but they are still not part of any release. I will create a release next week. For the error `render() is support only in each() query` - this means that `render()` could be called only inside `each()` binding because it is not useful elsewhere. I will show an example:

```html
<ul data-query="each([1, 2, 3])">
  <!-- render() could be used here -->
  <li data-query="render(true)"></li>
</ul>
```

**Comment by zombiQWERTY** [comment]
Ok, understood. But what about ifnot query?
And I need to function like Angular ng-if for partial rendering depending on different conditions. How can I do it?

**Comment by astoilkov** [comment]
`ifnot` query is working. It just logs incorrect messages to the console. This is fixed in the latest code. You could use `visible()` query to show and hide particular sections.

**Comment by zombiQWERTY** [comment]
Ok, thank you. Closed

**Comment by quantumlink** [comment]
Seems to me that the ability to conditionally not render elements in a view based on values from the view instead of just having to use `visible()` which just hides them using CSS is valuable and `render()` could be used for that.
One simple case I can think of is if there is an `img` tag where the model's value for the source is _falsey_ and it would be nice to just not include the `img` tag at all instead of just hiding it. 
In that case it would be `<img data-query="render(profile_img)" src="{{profile_img}}">`.
Perhaps there is another way to do this in jsblocks that I'm missing.

**Comment by astoilkov** [comment]
Thanks for the idea.

What the benefit of removing the <img> element would be? Are you using server-side rendering?

**Comment by quantumlink** [comment]
In this case I'm not using server-side rendering, was just looking for a solution the client-side that would allow me to exclude the element conditionally. A case would be if I loaded some data from localstore after a route change let's say and wanted to not include an element conditionally. I can see how in most cases `visible` is what you want, but in some cases, `img` tags being one, it's nice to have control over if the element shows up at all. I suppose I could just use some JS to remove the element from the logic in the view, but it would be nice to be able to have a `data-query` that allowed conditionally including elements.

**Comment by astoilkov** [comment]
Ahaa. Ok. I understand now. I agree and have created an issue for this [here](https://github.com/astoilkov/jsblocks/issues/83).

**Comment by quantumlink** [comment]
:+1: Really enjoying working with this framework, thank you for all your effort.
