### ISSUE TITLE
navigate to a view inside a view with navigateTo query

### ISSUE THREAD

**Issue by Kanaye** [astoilkov/jsblocks#75]
Hi!
I couldn't figure out how to navigate from one view to an other with the navigateTo()-query.
If it's not intended to work inside a view please add it to the documentation and add an more readable error then: "ReferenceError 'EnteredViewName' is not defined".
Example: [jsfiddle](http://jsfiddle.net/zx4sg1ch/6/)

Thank you and have a nice day!
Greetings from Germany
-Kanaye

**Comment by astoilkov** [comment]
Hi,

In order to fix your problem you will have to use $root to point to the application object `navigateTo($root.Test)`:

```html
<div data-query="view(Test)">
    <p>View: Test</p>
</div>
<div data-query="view(Start)">
    <p>View: Start</p>
    <a href="#" data-query="navigateTo($root.Test)">To view Test</a>
</div>
```

The reason for this behavior is the context being changed. The `Test` view is in the $root (Application) object and not inside of the `Start` view. If test would have been a child view of Start then your code would have worked. For more information on contexts you could read the [Context properties](http://jsblocks.com/learn/syntax-context-properties) help article.

**Comment by Kanaye** [comment]
Thank you for your quick help! 
Seems I have missed it, but thought there musst be something like that.
Closing this now.

Have a great day!
Greeting from Germany
-Kanaye
