### ISSUE TITLE
observable cannot survive JSON.stringify

### ISSUE THREAD

**Issue by lilchow** [astoilkov/jsblocks#86]
Let's say I created this simple object:

var a={};
a.obs=blocks.observable(2);

console.log(JSON.stringify(a)) would show only an empty object, i.e. "{}";

**Comment by astoilkov** [comment]
Hi @lilchow,

Sorry for the long long wait. I actually opened the issue and then forgot to answer it. The described behavior is expected. Observable objects are functions and JSON.stringify skips functions when stringifying objects.

In order to resolve your issue you could manually extract the values in an object and then call JSON.stringify.

```
var observable = blocks.observable(2);
var a = {};
a.obs = observable();
```

**Comment by Kanaye** [comment]
You could also write a JSON.stringify replacer function, like so [jsfiddle](https://jsfiddle.net/L7e0ysjb/5/).

@astoilkov Maybe some function like this should be integrated into jsblocks?

Have a great day

**Comment by astoilkov** [comment]
Yeah. I like that idea. I am thinking of something like `blocks.stringify` that has a built in helper function like the one demonstrated in the jsfiddle example. What do you think?

**Comment by Kanaye** [comment]
A `blocks.stringify` sounds good to me.
Maybe it should stay compatible to `JSON.stringify` and call the replacer function after replacing the observables.

**Comment by Kanaye** [comment]
Or we implement a ``toJSON`` function which returns a string or just the plain value.
I thought this way can't be cross browser compatible, but it works down to IE8 (I tested myself).
I think that way is better as it's not involving an function the user (or an other libary for e.g. ajax) has to call.
