### ISSUE TITLE
Uncaught TypeError: Cannot read property '_serverData' of undefined

### ISSUE THREAD

**Issue by astoilkov** [astoilkov/jsblocks#93]
http://plnkr.co/edit/4UgROWV8wHbqozP7IdRy?p=preview

**Comment by Kanaye** [comment]
This bug exsists because the ``blocks.clone`` method tries to create  new ``View`` without the right context/arguments. 
Possible ways to fix this:
- 1. Implement a ``cloneable`` or ``_clonable`` propertie that would (if exsists and false) prevent from cloning an instance.
Or
- 2. Let ``blocks.clone`` search for a ``clone`` method on objects and if exsists use that return value. In the ``App.View`` we could just return a reference because a view is a singleton.

Both atemps have the disadvantage that we would need to implement a wrapper function for lodash/underscore once we remove jsvalue.

What do you think ?

Btw. the ``clone`` method and other (namely currently ``debug.*``) are in the ``lib`` directory because they are originaly jsvalue/jscore functions. How should we handle modifications to them ?

**Comment by astoilkov** [comment]
Can you explain a little more? When and with what `blocks.clone` method is called so it tries to clone the `App.View` is there a way to just not call `clone` on the `App.View` object?

If the above is not possible I like the second idea more because not only fixes the problem but provides new functionality. Regarding the modifications there are two ways:
There is a private repository which have jsvalue inside.
  - I can do it
  - Or if it is interesting for you I can give you access to the private repository

**Comment by Kanaye** [comment]
In the example linked above, we have nested model that get's called with an exsisting instance of an other model (in the example it's the ``User`` model that get's called with an ``Car`` instance called ``newCar``).
The ``newCar`` instance will be cloned by the ``User`` constructor. 
The ``newCar`` has an property ``_application`` (btw. that might be the better position to place a ``clone`` method or ``_clonable`` flag mentioned above) that Application has the ``._views`` array.
When the views in that array get cloned the constructor does not get passed the right arguments and fails when calling ``View#_load()`` as that tries to access the property ``_serverData`` of the not passed ``Application`` instance.

When thinking about that we could also implement a check in the Model constructor if a passed argument is a Model instance and than handle it some other way.

Regarding access to the repository, I would love to get access.
It's normally easier to figure something out if you can see and modify all parts of it.
But in the end it's your dicission and I will respect it, as with every change I submit to the framework.

**Comment by astoilkov** [comment]
Perfect. I understand the problem now. I will give you access to the repository. I will do it tomorrow. 

Happy to see you are interested. :)

**Comment by astoilkov** [comment]
I invited you. You could try and run the project. If you have any difficulties running it let me know there.

**Comment by Kanaye** [comment]
Awesome! Thank you!
I will look into jsvalue deeper once I start to fix the bug related to it and when I have time again.
I created a PR for the clone change in the jscore repository.
I will push a PR containing the updated 'lib/blocks/core.js' and some other changes with clone implmentations, including the both mentioned above, probably tomorrow.
